steps:
# Step 1: Build the Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/liveramp-eng-qa-reliability/test-deploy/test_001:latest', '.' ]
  id: 'Build Docker Image'

# Step 2: Push the image to the Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-east1-docker.pkg.dev/liveramp-eng-qa-reliability/test-deploy/test_001:latest' ]
  id: 'Push Docker Image'


# Step 3: Deployment to Kubernetes Engine
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=us-east1
    gcloud deploy apply --file deploy/dev.yaml --region=us-central1
    gcloud deploy releases create 'app-release_${SHORT_SHA}' --delivery-pipeline='gke-cicd-pipeline' --region=us-central1 --skaffold-file=skaffold.yaml
  id: 'Deployment to Kubernetes Engine'
