apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    type: backend
    app: jas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: jas-app
  template:
    metadata:
      name: my-deployment
      labels:
        type: backend
        app: jas-app
    spec:
      containers:
        - name: my-container
          image: us-east1-docker.pkg.dev/liveramp-eng-qa-reliability/test-deploy/test_001:latest
          ports:
            - containerPort: 8080
